### ISSUE TITLE
Proposal: Restrictions on valid child types

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/chopsui#14]
I want the following to make sense:

```
grid
  row
    column
      ...
    column
      ...
```

The "grid" should restrict its valid children to just "row" (or perhaps "row" and "column" and adjust its flow direction automatically).

**Comment by GrayHatter** [comment]
I'm all for a stricter rule set. If you want to use grid, it's children need to be row, and row's children need to be column.

 If you want the option reflow horizontally, we could then add a matrix. of which you could require specification of size/direction. Giving a simple model that's easy, and an advanced model when you need finer grained control.

**Comment by SirCmpwn** [comment]
This is actually already possible via the `child` handler in the sui_type_impl.
